<HomeWidget@BoxLayout>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 0.8
        Line:
            rectangle: self.x+0.015*self.width, self.y+0.02*self.height, 0.97*self.width, 0.96*self.height
        Color:
            rgba: 1, 1, 1, 0.3
        Rectangle:
            size: 0.976*self.width, 0.96*self.height
            pos: self.x+0.012*self.width, self.y+0.022*self.height

    cols: 2
    orientation: 'vertical'
