server:
  port: 8070

spring:
  application:
    name: EarPi
  cloud:
    consul:
      host: "localhost"
      port: 8500

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
