#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport


class Iface(object):
    def handleRequest(self, input):
        """
        Parameters:
         - input
        """
        pass

    def confimFace(self, input):
        """
        Parameters:
         - input
        """
        pass

    def writeLog(self, input):
        """
        Parameters:
         - input
        """
        pass

    def ping(self, pingObject):
        """
        Parameters:
         - pingObject
        """
        pass

    def login(self, loginObject):
        """
        Parameters:
         - loginObject
        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def handleRequest(self, input):
        """
        Parameters:
         - input
        """
        self.send_handleRequest(input)
        return self.recv_handleRequest()

    def send_handleRequest(self, input):
        self._oprot.writeMessageBegin('handleRequest', TMessageType.CALL, self._seqid)
        args = handleRequest_args()
        args.input = input
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_handleRequest(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = handleRequest_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.endPointUnavailiable is not None:
            raise result.endPointUnavailiable
        if result.thriftException is not None:
            raise result.thriftException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "handleRequest failed: unknown result")

    def confimFace(self, input):
        """
        Parameters:
         - input
        """
        self.send_confimFace(input)

    def send_confimFace(self, input):
        self._oprot.writeMessageBegin('confimFace', TMessageType.ONEWAY, self._seqid)
        args = confimFace_args()
        args.input = input
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def writeLog(self, input):
        """
        Parameters:
         - input
        """
        self.send_writeLog(input)

    def send_writeLog(self, input):
        self._oprot.writeMessageBegin('writeLog', TMessageType.ONEWAY, self._seqid)
        args = writeLog_args()
        args.input = input
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def ping(self, pingObject):
        """
        Parameters:
         - pingObject
        """
        self.send_ping(pingObject)
        self.recv_ping()

    def send_ping(self, pingObject):
        self._oprot.writeMessageBegin('ping', TMessageType.CALL, self._seqid)
        args = ping_args()
        args.pingObject = pingObject
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_ping(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = ping_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.endPointUnavailiable is not None:
            raise result.endPointUnavailiable
        if result.thriftException is not None:
            raise result.thriftException
        return

    def login(self, loginObject):
        """
        Parameters:
         - loginObject
        """
        self.send_login(loginObject)
        return self.recv_login()

    def send_login(self, loginObject):
        self._oprot.writeMessageBegin('login', TMessageType.CALL, self._seqid)
        args = login_args()
        args.loginObject = loginObject
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_login(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = login_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.bad is not None:
            raise result.bad
        if result.fail is not None:
            raise result.fail
        raise TApplicationException(TApplicationException.MISSING_RESULT, "login failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["handleRequest"] = Processor.process_handleRequest
        self._processMap["confimFace"] = Processor.process_confimFace
        self._processMap["writeLog"] = Processor.process_writeLog
        self._processMap["ping"] = Processor.process_ping
        self._processMap["login"] = Processor.process_login

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_handleRequest(self, seqid, iprot, oprot):
        args = handleRequest_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = handleRequest_result()
        try:
            result.success = self._handler.handleRequest(args.input)
            msg_type = TMessageType.REPLY
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except ThriftException.ttypes.ExternalEndpointUnavailable as endPointUnavailiable:
            msg_type = TMessageType.REPLY
            result.endPointUnavailiable = endPointUnavailiable
        except ThriftException.ttypes.ThriftServiceException as thriftException:
            msg_type = TMessageType.REPLY
            result.thriftException = thriftException
        except Exception as ex:
            msg_type = TMessageType.EXCEPTION
            logging.exception(ex)
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("handleRequest", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_confimFace(self, seqid, iprot, oprot):
        args = confimFace_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.confimFace(args.input)
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except:
            pass

    def process_writeLog(self, seqid, iprot, oprot):
        args = writeLog_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.writeLog(args.input)
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except:
            pass

    def process_ping(self, seqid, iprot, oprot):
        args = ping_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = ping_result()
        try:
            self._handler.ping(args.pingObject)
            msg_type = TMessageType.REPLY
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except ThriftException.ttypes.ExternalEndpointUnavailable as endPointUnavailiable:
            msg_type = TMessageType.REPLY
            result.endPointUnavailiable = endPointUnavailiable
        except ThriftException.ttypes.ThriftServiceException as thriftException:
            msg_type = TMessageType.REPLY
            result.thriftException = thriftException
        except Exception as ex:
            msg_type = TMessageType.EXCEPTION
            logging.exception(ex)
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("ping", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_login(self, seqid, iprot, oprot):
        args = login_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = login_result()
        try:
            result.success = self._handler.login(args.loginObject)
            msg_type = TMessageType.REPLY
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except ThriftException.ttypes.BadHashException as bad:
            msg_type = TMessageType.REPLY
            result.bad = bad
        except ThriftException.ttypes.LoginFailedException as fail:
            msg_type = TMessageType.REPLY
            result.fail = fail
        except Exception as ex:
            msg_type = TMessageType.EXCEPTION
            logging.exception(ex)
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("login", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class handleRequest_args(object):
    """
    Attributes:
     - input
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'input', (EyePiInput, EyePiInput.thrift_spec), None, ),  # 1
    )

    def __init__(self, input=None,):
        self.input = input

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.input = EyePiInput()
                    self.input.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('handleRequest_args')
        if self.input is not None:
            oprot.writeFieldBegin('input', TType.STRUCT, 1)
            self.input.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class handleRequest_result(object):
    """
    Attributes:
     - success
     - endPointUnavailiable
     - thriftException
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (EyePiOutput, EyePiOutput.thrift_spec), None, ),  # 0
        (1, TType.STRUCT, 'endPointUnavailiable', (ThriftException.ttypes.ExternalEndpointUnavailable, ThriftException.ttypes.ExternalEndpointUnavailable.thrift_spec), None, ),  # 1
        (2, TType.STRUCT, 'thriftException', (ThriftException.ttypes.ThriftServiceException, ThriftException.ttypes.ThriftServiceException.thrift_spec), None, ),  # 2
    )

    def __init__(self, success=None, endPointUnavailiable=None, thriftException=None,):
        self.success = success
        self.endPointUnavailiable = endPointUnavailiable
        self.thriftException = thriftException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = EyePiOutput()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.endPointUnavailiable = ThriftException.ttypes.ExternalEndpointUnavailable()
                    self.endPointUnavailiable.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.thriftException = ThriftException.ttypes.ThriftServiceException()
                    self.thriftException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('handleRequest_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.endPointUnavailiable is not None:
            oprot.writeFieldBegin('endPointUnavailiable', TType.STRUCT, 1)
            self.endPointUnavailiable.write(oprot)
            oprot.writeFieldEnd()
        if self.thriftException is not None:
            oprot.writeFieldBegin('thriftException', TType.STRUCT, 2)
            self.thriftException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class confimFace_args(object):
    """
    Attributes:
     - input
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'input', (ConfirmInput, ConfirmInput.thrift_spec), None, ),  # 1
    )

    def __init__(self, input=None,):
        self.input = input

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.input = ConfirmInput()
                    self.input.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('confimFace_args')
        if self.input is not None:
            oprot.writeFieldBegin('input', TType.STRUCT, 1)
            self.input.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class writeLog_args(object):
    """
    Attributes:
     - input
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'input', (EyePiInput, EyePiInput.thrift_spec), None, ),  # 1
    )

    def __init__(self, input=None,):
        self.input = input

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.input = EyePiInput()
                    self.input.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('writeLog_args')
        if self.input is not None:
            oprot.writeFieldBegin('input', TType.STRUCT, 1)
            self.input.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class ping_args(object):
    """
    Attributes:
     - pingObject
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'pingObject', (GenericStruct.ttypes.PingObject, GenericStruct.ttypes.PingObject.thrift_spec), None, ),  # 1
    )

    def __init__(self, pingObject=None,):
        self.pingObject = pingObject

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.pingObject = GenericStruct.ttypes.PingObject()
                    self.pingObject.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('ping_args')
        if self.pingObject is not None:
            oprot.writeFieldBegin('pingObject', TType.STRUCT, 1)
            self.pingObject.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class ping_result(object):
    """
    Attributes:
     - endPointUnavailiable
     - thriftException
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'endPointUnavailiable', (ThriftException.ttypes.ExternalEndpointUnavailable, ThriftException.ttypes.ExternalEndpointUnavailable.thrift_spec), None, ),  # 1
        (2, TType.STRUCT, 'thriftException', (ThriftException.ttypes.ThriftServiceException, ThriftException.ttypes.ThriftServiceException.thrift_spec), None, ),  # 2
    )

    def __init__(self, endPointUnavailiable=None, thriftException=None,):
        self.endPointUnavailiable = endPointUnavailiable
        self.thriftException = thriftException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.endPointUnavailiable = ThriftException.ttypes.ExternalEndpointUnavailable()
                    self.endPointUnavailiable.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.thriftException = ThriftException.ttypes.ThriftServiceException()
                    self.thriftException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('ping_result')
        if self.endPointUnavailiable is not None:
            oprot.writeFieldBegin('endPointUnavailiable', TType.STRUCT, 1)
            self.endPointUnavailiable.write(oprot)
            oprot.writeFieldEnd()
        if self.thriftException is not None:
            oprot.writeFieldBegin('thriftException', TType.STRUCT, 2)
            self.thriftException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class login_args(object):
    """
    Attributes:
     - loginObject
    """

    thrift_spec = (
        None,  # 0
        (1, TType.STRUCT, 'loginObject', (LoginInputObject, LoginInputObject.thrift_spec), None, ),  # 1
    )

    def __init__(self, loginObject=None,):
        self.loginObject = loginObject

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.loginObject = LoginInputObject()
                    self.loginObject.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('login_args')
        if self.loginObject is not None:
            oprot.writeFieldBegin('loginObject', TType.STRUCT, 1)
            self.loginObject.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class login_result(object):
    """
    Attributes:
     - success
     - bad
     - fail
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (LoginOutputObject, LoginOutputObject.thrift_spec), None, ),  # 0
        (1, TType.STRUCT, 'bad', (ThriftException.ttypes.BadHashException, ThriftException.ttypes.BadHashException.thrift_spec), None, ),  # 1
        (2, TType.STRUCT, 'fail', (ThriftException.ttypes.LoginFailedException, ThriftException.ttypes.LoginFailedException.thrift_spec), None, ),  # 2
    )

    def __init__(self, success=None, bad=None, fail=None,):
        self.success = success
        self.bad = bad
        self.fail = fail

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = LoginOutputObject()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.bad = ThriftException.ttypes.BadHashException()
                    self.bad.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.fail = ThriftException.ttypes.LoginFailedException()
                    self.fail.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('login_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.bad is not None:
            oprot.writeFieldBegin('bad', TType.STRUCT, 1)
            self.bad.write(oprot)
            oprot.writeFieldEnd()
        if self.fail is not None:
            oprot.writeFieldBegin('fail', TType.STRUCT, 2)
            self.fail.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
